CREATE TABLE exportcat(
   Category_Name VARCHAR(50) 
  ,Quantity      VARCHAR(50) NOT NULL
  ,Amount        VARCHAR(50) NOT NULL
);
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('accessoires','7189','54.257,69');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('accessoires','61','998.84');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('alle producten','1098','7.597,17');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('bestek','3918','9.243,20');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('borden','13510','141.492,96');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('cadeaubon','32','1.622,50');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('coupes','11','162.96');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('dinerborden','3468','57.629,96');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('eierdoppen','53','555.56');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('espresso','5253','18.889,82');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('gebaksborden','1007','13.843,90');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('geschenksets','55','2.359,06');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('glas','1735','14.889,28');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('glas','118','1.723,89');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('glazen kannen en karaffen','326','5.046,27');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('grote kommen Ø 17-20 cm','2111','30.020,44');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('kandelaars en kaarsen','434','3.696,82');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('kannen en karaffen','1402','19.098,75');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('kannen en karaffen','316','4.867,43');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('keramiek kannen','1076','14.052,49');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('kleine kommen Ø 11-14 cm','2656','17.146,54');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('kleine schaaltjes','114','1.412,22');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('kleurstalen','101','342.82');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('koffie en thee','78','1.305,81');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('koffie- en theepotten','16','251.44');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('koffie- en theeservies','26','357.56');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('koffie-/theepot','17','291.39');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('kommen','5610','55.415,64');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('kommen','105','843.68');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('kop &amp; schotels','1446','8.856,54');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('kopjes','5634','21.497,57');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('medium kommen Ø 14-17 cm','781','7.298,93');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('mini bordjes','1585','11.401,71');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('mini kommen Ø 8-11 cm','63','969.68');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('mokken','6056','35.259,98');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('mokken en kopjes','20882','86.170,28');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('nieuwe kleuren','560','3.384,40');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('nieuwe producten','433','5.053,71');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('onderborden','533','6.114,38');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('ontbijtborden','4552','41.161,12');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('outlet','105','697.33');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('overige borden','98','7.028,56');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('overige drinkglazen','45','640.02');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('overige kommen','1','9.95');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('pastaborden','2524','30.400,47');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('placemats','835','17.095,07');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('placemats','834','17.086,11');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('schalen','235','3.667,45');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('serveerbestek','727','3.816,46');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('serveerplanken','1','16.49');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('serveerschalen','121','2.255,23');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('servetten','143','1.845,64');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('servies','40124','284.705,46');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('servies','65','1.044,63');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('suiker en melk','13','161.98');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('suiker en melk','12','150.03');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('tafelbestek','3191','5.426,74');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('tafelkleden','57','3.414,10');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('tafellinnen','1037','22.444,90');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('tafellinnen','4','123.80');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('tafellopers','3','99.05');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('tapas bordjes','95','1.142,34');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('theelepels','3094','3.816,26');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('vazen','524','4.255,55');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('Verberg product','822','676.83');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('vintage','298','4.770,70');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('waterglazen','1206','9.508,13');
INSERT INTO exportcat(Category_Name,Quantity,Amount) VALUES ('wijnglazen','123','2.036,34');
